---
# tasks file for monitoring_role

- name: Create a network
  community.docker.docker_network:
    name: prometheus-network

- name: Start Grafana
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:8.0.6
    restart_policy: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
    - name: prometheus-network

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/roi/prometheus
    state: directory
    mode: '0755'
    owner: roi

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /home/roi/prometheus
    mode: '0755'
    owner: roi

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/roi/prometheus/prometheus-data
    state: directory
    mode: '0755'
    owner: roi

- name: Start Prometheus
  community.docker.docker_container:
    user: "1000:1000"
    name: prometheus
    image: prom/prometheus:v2.28.1
    restart_policy: unless-stopped
    volumes:
    - /home/roi/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - /home/roi/prometheus/prometheus-data:/prometheus
    ports:
    - 9090:9090
    networks:
    - name: prometheus-network
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=1y'
    - '--web.enable-lifecycle'

- name: Start node_exporter
  community.docker.docker_container:
    name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    restart_policy: unless-stopped
    ports:
    - 9100:9100
    networks:
    - name: prometheus-network
    ##### linux
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'

- name: Start Cadvisor
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart_policy: unless-stopped
    expose:
    - 8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
    - name: prometheus-network
