---
# tasks file for docker-install-role
- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    
- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present

- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  #notify: Start docker on boot

- name: Add remote user to "docker" group
  user:
    name: "{{ user_name }}"
    group: "docker"
    append: yes

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Enable docker on startup
  service:
    name: docker
    enabled: yes
